#!/bin/bash

# This script attempts to garbage collect docker containers and images.
# Containers that exited more than an hour ago are removed.
# Images that have existed more than an hour and are not in use by any
# containers are removed.

# Note: Although docker normally prevents removal of images that are in use by
#       containers, we take extra care to not remove any image tags (e.g.
#       ubuntu:14.04, busybox, etc) that are used by containers. A naive
#       "docker rmi `docker images -q`" will leave images stripped of all tags,
#       forcing users to re-pull the repositories even though the images
#       themselves are still on disk.

# Note: State is stored in $STATE_DIR, defaulting to /var/lib/docker-gc

set -o nounset
set -o errexit

GRACE_PERIOD_SECONDS=${GRACE_PERIOD_SECONDS:=3600}
STATE_DIR=${STATE_DIR:=/var/lib/docker-gc}
DOCKER=${DOCKER:=docker}

# Elapsed time since a docker timestamp, in seconds
function ElapsedTime() {
    python <<END
from datetime import datetime,timedelta
now = datetime.utcnow()
exited =  datetime.strptime("${1}".replace("Z","").split('.')[0], "%Y-%m-%dT%H:%M:%S")
print int((now - exited).total_seconds())
END
}


cd "$STATE_DIR"

# Verify that docker is reachable
$DOCKER version 1>/dev/null

# List all currently existing containers
$DOCKER ps -a -q --no-trunc | sort | uniq > containers.all

# List running containers
$DOCKER ps -q --no-trunc | sort | uniq > containers.running

# List containers that are not running
comm -23 containers.all containers.running > containers.exited

# Find exited containers that finished at least GRACE_PERIOD_SECONDS ago
echo -n "" > containers.reap.tmp
cat containers.exited | while read line
do
    EXITED=$(docker inspect -f '{{.State.FinishedAt}}' ${line})
    ELAPSED=$(ElapsedTime $EXITED)
    if [[ $ELAPSED -gt $GRACE_PERIOD_SECONDS ]]; then
        echo $line >> containers.reap.tmp
    fi
done
cat containers.reap.tmp | sort | uniq > containers.reap

# List containers that we will keep.
comm -23 containers.all containers.reap > containers.keep

# List images used by containers that we keep.
# This may be both image id's and repo/name:tag, so normalize to image id's only
cat containers.keep |
xargs -r -n 1 docker inspect -f '{{.Config.Image}}' 2>/dev/null |
sort | uniq |
xargs -r -n 1 docker inspect -f '{{.Id}}' 2>/dev/null |
sort | uniq > images.used

# List images to reap; images that existed last run and are not in use.
$DOCKER images -q --no-trunc | sort | uniq > images.all
comm -23 images.all images.used > images.reap

# Reap containers.
xargs -r -n 1 $DOCKER rm --volumes=true < containers.reap &>/dev/null

# Reap images.
xargs -r -n 1 $DOCKER rmi < images.reap &>/dev/null

